### ISSUE TITLE
【Security】vue-json-pretty has xss vulnerability

### ISSUE THREAD

**Issue by liode1s** [leezng/vue-json-pretty#150]
My Local environment vue-json-pretty 1.8.2 it is vuejs library lastest

this is demo 
```html
<template>
  <div>
    <div>
      <vue-json-pretty :deep="3" :data="testdata" show-line="false" />
    </div>
  </div>
</template>

<script>
import VueJsonPretty from 'vue-json-pretty'
import 'vue-json-pretty/lib/styles.css'

export default {
  components: { VueJsonPretty },
  data() {
    return {
      testdata: '{ a: "\r\n<img/src=x onerror=prompt(x)>" }'
    }
  }
}
```
then you can see this
![image](https://user-images.githubusercontent.com/26197815/142372558-73ebd688-3104-46b4-a05a-bd37b4a526ee.png)

This problem also exists, but it does not exist by default, but you need to turn on use custom formatter

![image](https://user-images.githubusercontent.com/26197815/142374332-fbbbc472-f4d4-4fb4-92f5-f9e95207ee26.png)

**Comment by leezng** [comment]
https://vuejs.org/v2/api/#v-html

**Comment by LiodAir** [comment]
I don't think you should turn off this problem. There are too many input source data, and ordinary developers will not consider whether to escape special symbols. This attack feature exists due to the default use of v-html winding. You want to format the output characters when winding by default instead of rendering the whole content v-html. thanks

**Comment by LiodAir** [comment]
json parse is use v-text is default template. when use use custom formater to change template

**Comment by souljorje** [comment]
@leezng you should reopen this
