### ISSUE TITLE
Hi, I am using Vue2 with this library, some days ago it's working, but recently, I am facing below errors, Please help!

### ISSUE THREAD

**Issue by mccccccmike** [leezng/vue-json-pretty#189]
![image](https://user-images.githubusercontent.com/11752382/185099679-c46d4fba-4ffc-4fd4-9b31-a9ea2cb33e6b.png)

**Comment by ibrahimabtula** [comment]
I started getting same error from today.

**Comment by leezng** [comment]
Sorry for this problem, this is because the optional chain syntax is used in the new version. During the build process, since the newer versions of most major browsers are already supported, webpack does not handle the compatibility.

If it is currently not recognized in your project, you can temporarily hack `vue-json-pretty.js` by adding the babel plugin `@babel/plugin-proposal-optional-chaining`.

Note, I will be dealing with this compatibility issue in 1.9.1.

**Comment by Carl0608** [comment]
This will be resolved in version 1.7.0

**Comment by ibrahimabtula** [comment]
Thank you
