### ISSUE TITLE
Missing serial number

### ISSUE THREAD

**Issue by shijunti19** [leezng/vue-json-pretty#25]
1.Missing serial number

![image](https://user-images.githubusercontent.com/5392211/56092592-8cdd8300-5ef0-11e9-96ae-dff9bdf44555.png)

2.Want to add, modify and delete data (preferably mobile)

3.Let's get the formatted string and paste it into the blog

**Comment by shijunti19** [comment]
Want to add, modify and delete data (preferably mobile)

**Comment by leezng** [comment]
Can you provide the JSON data or online demo?

**Comment by shijunti19** [comment]
@leezng I'm talking about requirements. When I make a JSON error, I should show the serial number.

**Comment by leezng** [comment]
You can use `try catch` to catch errors, because in general the component does not need to verify the error, such as the JSON data returned by the server. This format is usually ok. If the component needs to check the format every time, in this scenario Will affect performance.

I think the component provides a configuration that gives the user a better way to choose whether or not to perform format verification. But at the moment, you can handle it as I said.
